name: Release PDF

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install LaTeX dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended

      - name: Compile LaTeX document
        run: |
          latexmk handouts/presentacion-coloquio-2025-isra.tex

      - name: Create release
        id: create-release
        uses: peter-evans/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-artifact@v3
        with:
          name: presentacion-coloquio-2025-isra.pdf
          path: handouts/presentacion-coloquio-2025-isra.pdf
          if-no-files-found: error

      - name: Upload release asset to release
        uses: peter-evans/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_ID: ${{ steps.create-release.outputs.id }}
        with:
          asset_path: ./handouts/presentacion-coloquio-2025-isra.pdf
          asset_name: presentacion-coloquio-2025-isra.pdf
          asset_type: application/pdf

